# Скрипт оптимизированной сборки PWA для SakhaLive Radio
# Версия: 2.0.0

Write-Host "🚀 SakhaLive PWA Optimized Build" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan

# Очистка перед сборкой
Write-Host "`n🧹 Cleaning build cache..." -ForegroundColor Yellow
flutter clean

# Получение зависимостей
Write-Host "`n📦 Getting dependencies..." -ForegroundColor Yellow
flutter pub get

# Генерация сплэша
Write-Host "`n✨ Generating native splash..." -ForegroundColor Yellow
dart run flutter_native_splash:create

# Генерация иконок
Write-Host "`n🎨 Generating launcher icons..." -ForegroundColor Yellow
dart run flutter_launcher_icons

# Генерация локализации
Write-Host "`n🌐 Generating localizations..." -ForegroundColor Yellow
flutter gen-l10n

# Анализ кода
Write-Host "`n🔍 Analyzing code..." -ForegroundColor Yellow
flutter analyze

# Сборка web-версии с оптимизациями
Write-Host "`n🏗 Building PWA with optimizations..." -ForegroundColor Green

# Ключевые флаги оптимизации:
# --release: Режим релиза (включает tree-shaking, minification)
# --csp: Включает CSP совместимость (отключает eval)
# --no-source-maps: Не генерировать source maps (уменьшает размер)
flutter build web `
  --release `
  --csp `
  --no-source-maps

# Проверка размера сборки
Write-Host "`n📊 Build size analysis:" -ForegroundColor Cyan
$buildDir = "build/web"
if (Test-Path $buildDir) {
  $totalSize = (Get-ChildItem $buildDir -Recurse -File | Measure-Object -Property Length -Sum).Sum
  $totalSizeMB = [math]::Round($totalSize / 1MB, 2)
  Write-Host "Total build size: $totalSizeMB MB" -ForegroundColor $(if ($totalSizeMB -lt 5) { "Green" } elseif ($totalSizeMB -lt 10) { "Yellow" } else { "Red" })
  
  # Топ-5 самых больших файлов
  Write-Host "`nTop 5 largest files:" -ForegroundColor Yellow
  Get-ChildItem $buildDir -Recurse -File | 
    Sort-Object Length -Descending | 
    Select-Object -First 5 | 
    ForEach-Object {
      $sizeMB = [math]::Round($_.Length / 1MB, 2)
      Write-Host "  $($_.Name): $sizeMB MB" -ForegroundColor Gray
    }
}

# Проверка service worker
Write-Host "`n🔍 Checking Service Worker..." -ForegroundColor Cyan
$swPath = Join-Path $buildDir "flutter_service_worker.js"
if (Test-Path $swPath) {
  Write-Host "✅ Service Worker found (generated by Flutter)" -ForegroundColor Green
} else {
  Write-Host "❌ Service Worker not found!" -ForegroundColor Red
}

Write-Host "`n✅ Build completed successfully!" -ForegroundColor Green
Write-Host "`n📁 Build location: build/web" -ForegroundColor Cyan
Write-Host "`n🚀 To deploy:" -ForegroundColor Cyan
Write-Host "  firebase deploy --only hosting" -ForegroundColor Gray
Write-Host "`n🧪 To test locally:" -ForegroundColor Cyan
Write-Host "  npx serve build/web" -ForegroundColor Gray
