org.gradle.jvmargs=-Xmx12G -XX:MaxMetaspaceSize=6G -XX:ReservedCodeCacheSize=1G -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true

# Включает Gradle Daemon для быстрой повторной сборки
org.gradle.daemon=true
# Включает параллельную сборку проектов
org.gradle.parallel=true
# Отключаем Gradle Enterprise (требует подключения к серверу)
org.gradle.gradleenterprise.enabled=false
# Отключаем Build Cache для работы без сети
org.gradle.caching=false
# Ускоряет сборку в многомодульных проектах
android.nonTransitiveRClass=true

# Оптимизации для Kotlin
kotlin.incremental=false
kotlin.caching.enabled=false
kotlin.parallel.tasks.in.project=true

# Оптимизации для Android
android.enableD8=true
android.enableR8.fullMode=false
android.useNewApkCreator=true

# Оптимизации для Flutter
flutter.buildMode=release
