// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsP4btD3tfm9nOESW0YdCyVWYCJmmnBME',
    appId: '1:1097107309921:web:72ee1a1fd96448f62d3120',
    messagingSenderId: '1097107309921',
    projectId: 'sakhalive-ticker',
    authDomain: 'sakhalive-ticker.firebaseapp.com',
    databaseURL: 'https://sakhalive-ticker-default-rtdb.firebaseio.com',
    storageBucket: 'sakhalive-ticker.firebasestorage.app',
    measurementId: 'G-XZ80DE36V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApqgccLr4zrPFv5PIXgQiJa4BKfSRkw7Q',
    appId: '1:1097107309921:android:7a5c8b928ec2005c2d3120',
    messagingSenderId: '1097107309921',
    projectId: 'sakhalive-ticker',
    databaseURL: 'https://sakhalive-ticker-default-rtdb.firebaseio.com',
    storageBucket: 'sakhalive-ticker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPB2X2ke21Smr0vqSczfwRtM-dolvyPyA',
    appId: '1:1097107309921:ios:b8fb3ac41625f5ac2d3120',
    messagingSenderId: '1097107309921',
    projectId: 'sakhalive-ticker',
    databaseURL: 'https://sakhalive-ticker-default-rtdb.firebaseio.com',
    storageBucket: 'sakhalive-ticker.firebasestorage.app',
    iosBundleId: 'com.yourname.sakhaRadio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsP4btD3tfm9nOESW0YdCyVWYCJmmnBME',
    appId: '1:1097107309921:web:43b1cd2d37c9f9822d3120',
    messagingSenderId: '1097107309921',
    projectId: 'sakhalive-ticker',
    authDomain: 'sakhalive-ticker.firebaseapp.com',
    databaseURL: 'https://sakhalive-ticker-default-rtdb.firebaseio.com',
    storageBucket: 'sakhalive-ticker.firebasestorage.app',
    measurementId: 'G-ZGSXJBQWX2',
  );

}